[tool.poetry]
name = "pyasic-api"
version = "0.1.0"
description = ""
authors = ["UpstreamData <brett@upstreamdata.ca>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyasic = "^0.19.0"
fastapi = {extras = ["uvicorn"], version = "^0.85.2"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
